### ISSUE TITLE
Design Question - React Router + Store

### ISSUE THREAD

**Issue by chrismcv** [hellyeahllc/exim#30]
Hi, 
I'm currently making a "Login Store" that manages my login screen, and I think it should also be responsible for doing route transitioning.  The seemingly ubiquitous way to do that in `react-router` is to  `mixin:[Router.Navigation]`.  This doesn't seem to work on store.  So I mixed into my view, and then check @state.loggedIn on my render calls - which works fine.  This doesn't feel quite right though.  Have you any advise?

Thanks,
Chris

**Comment by paulmillr** [comment]
Good catch. We should allow something like this in stores.

**Comment by paulmillr** [comment]
In the meantime, probably you'll need to move it from the store

**Comment by yavorsky** [comment]
@chrismcv Yes. It's really store's omission. 
For now, you can do something like: 

**store:** 
```javascript
onAction: function (args) {
  var data = args.data;
  //make something with data..
  var tr = args.transitonTo;
  tr('dashboard')
}
```

**component:**
```javascript
mixins: [Router.Navigation],
someAction: function () {
  stores.actions.action({data:{}, transitionTo:this.transitionTo})
}
```

**Comment by hotzenklotz** [comment]
:+1: 
I ran into the same problem. I would be nice to be able to just import the router module anywhere (not just components) and have an API to navigate to various page. I don't like how you have to rely on a dedicated component just simple routing.

**Comment by yavorsky** [comment]
Now, you can use:

**component**

```
store.actions.actionName().then => @transitionTo
```

**Comment by chrismcv** [comment]
Awesome :-)

**Comment by yavorsky** [comment]
@chrismcv :+1:
