### ISSUE TITLE
npm friendly version

### ISSUE THREAD

**Issue by chrismcv** [hellyeahllc/exim#32]
Hi, 
I haven't taken an update in a while.  

The latest version doesn't seem to work with npm/webpack.  When i `var exim = require('exim');` it is setting window.Exim = ... and my `exim` variable isn't usable.  Is there anything can be done to resolve that?

Thanks, 
Chris

**Comment by yavorsky** [comment]
Sorry for delay. [0.6.3](https://github.com/hellyeahllc/exim/commit/8313df266c438e56687d27c87941b0164758d59f) must fix this.

**Comment by chrismcv** [comment]
Sorry, took my time getting round to test this.

I'm afriad it's still not working with webpack....

Below is some of the wrapped output I'm seeing... `global == window` and exports == `Object {}`

I think exim is still being set on global rather than exports...

```
 })({1: [function(require, module, exports) {
                (function(global) {
                    "use strict";
                    
                    var _interopRequire = function(obj) {
                        return obj && obj.__esModule ? obj["default"] : obj;
                    };
                    
                    var _Actions = require("./Actions");
```

**Comment by yavorsky** [comment]
@chrismcv oh, sorry. Going to fix!

**Comment by chrismcv** [comment]
#33 might help with this, unless you don't like it!

**Comment by yavorsky** [comment]
@chrismcv Thank you!)
