### ISSUE TITLE
Problem with nested set

### ISSUE THREAD

**Issue by chrismcv** [hellyeahllc/exim#35]
Hi, 
Trying to hook latest version into existing app that was using old version of exim....

When running
```
console.log(AuthStore.connect().getInitialState())
```
I get 
```
Object {}
  __proto__: Object
    authenticated: true
    authenticating: false
    user: Object
    __proto__: Object
```

which then means that `this.state.user` is undefined on my view.

Store code for reference:
```
module.exports = Exim.createStore
  actions: ['login']

  initial:
    authenticating: true
    login: {}
    user:
      location: {}
    newPassword: {
      loading:true
    }

  login: (login, transitionTo, failedLogin) ->
    @set loading:true
    success = (res) =>
        res = res.body
        if res.requiresUserRegistration
          @set
            loading:false
          transitionTo 'verify'
        else if res.isAuthenticated
          @set
            loading:false
            authenticating: false
            authenticated: res.isAuthenticated
            user:
              name: res.name
              email:res.email
              location:res.location || {}
          transitionTo '/'
    error = (err) =>
        @set
          loading:false,
          login:
            userName:login.userName
            password:''
          message: 'There was a problem logging you in, please try again shortly'
        failedLogin? 'There was a problem logging you in, please try again shortly'
    http.post '/api/auth/credentials', login
      .then success
      .catch error
```

Is there something I'm doing wrong?

Thanks,
Chris

**Comment by chrismcv** [comment]
Now that you merged #36, I've got a simple recreate...  

https://github.com/tm2/exim/commit/a02fee11227996dd16058969b9490fc8bbc580ef

`Uncaught TypeError: Cannot read property 'email' of undefined`

`console.log(this.state)` yields `Object {fetching: false, error: null, data: null, word: "Hello"}`

Looks like a problem with nested objects...  still investigating... but any advise welcome.

**Comment by chrismcv** [comment]
```
   const setValue = function (key, value) {
      const correctArgs = ['key', 'value'].every(item => typeof item === 'string');
      return (correctArgs) ? store[key] = value : false;
    };
```
OK - this seems to be the problem.  if doing a nested set e.g.
```
this.set({user:{email:'test'}});
```
`correctArgs` will return false, preventing the object from being updated.

Is this an intentional design decision now?  As if so, it will cause me big problems throughout.

**Comment by paulmillr** [comment]
I don't see any reason to not support nested objects. Asking @yavorsky what was the motivation here since he coded the function.

**Comment by paulmillr** [comment]
Just dig into other places — I really think we can remove it.

**Comment by paulmillr** [comment]
Actually that's not the case.

```
      var correctArgs = ["key", "value"].every(function (item) {
        return typeof item === "string";
      });
```

We're checking `['key', 'value']` instead of `[key, value]` -- seems like a typo to me though

**Comment by chrismcv** [comment]
but if `value` is `{email:'test'}` then `correctArgs will be false, and setValue has no recursive aspect....

**Comment by paulmillr** [comment]
Again. This *always* returns true; launch it in your browser console:

```javascript
var correctArgs = ["key", "value"].every(function (item) {
  return typeof item === "string";
});
```

**Comment by chrismcv** [comment]
ah yes... sorry.... not paying attention

**Comment by chrismcv** [comment]
#37
