### ISSUE TITLE
Object.assign issues

### ISSUE THREAD

**Issue by chrismcv** [hellyeahllc/exim#39]
Hi, 
This one is partly my fault...

https://github.com/hellyeahllc/exim/blob/master/src/Store.js#L9
https://github.com/hellyeahllc/exim/blob/master/src/Store.js#L38

We're using `Object.assign(initial)` incorrectly here - it should be `Object.assign({}, initial)`.

This breaks at least `reset()` that I've noticed so far.

I can submit a PR for this.  However, my other issue is that we've noticed that even with the correct Object.assign usage, arrays aren't getting cloned.  I'd like your advice on 
1. should this be handled?
2. how should we?

There are a variety of cloning libs/utils that could be easily included or added as deps.  Alternatively, we could switch to Immutable/Freezer/Cortex as per #25 . Or we could make initial always have to be a function, and store the function rather than the object ref.  

I'm happy to do the work to make this happen, but think some discussion is needed first.

Thanks, 
Chris

**Comment by paulmillr** [comment]
Let's try freezer!

**Comment by paulmillr** [comment]
> store the function rather than the object ref

Actually this should work *for now*. Let's do this and then the freezer.

**Comment by yavorsky** [comment]
:+1:

**Comment by chrismcv** [comment]
playing with the freezer atm... will keep you posted....

**Comment by chrismcv** [comment]
#40

**Comment by paulmillr** [comment]
Closed?
