### ISSUE TITLE
Chat example - npm install fails

### ISSUE THREAD

**Issue by tiemevanveen** [hellyeahllc/exim#52]
npm install in root folder succeeds but the install in /examples/chat fails: 

    <removed>

Looks like this is caused by a dependency using an old version of `utf-8-validate`..

Bower install succeeds:

    $ bower install

    bower react#~0.12.1             cached git://github.com/facebook/react-bower.git#0.12.2
    bower react#~0.12.1           validate 0.12.2 against git://github.com/facebook/react-bower.git#~0.12.1
    bower react-router#*            cached git://github.com/rackt/react-router.git#1.0.2
    bower react-router#*          validate 1.0.2 against git://github.com/rackt/react-router.git#*
    bower bluebird#~2.3.6           cached git://github.com/petkaantonov/bluebird.git#2.3.11
    bower bluebird#~2.3.6         validate 2.3.11 against git://github.com/petkaantonov/bluebird.git#~2.3.6

    bower react#~0.12.1            install react#0.12.2
    bower react-router#*           install react-router#1.0.2
    bower bluebird#~2.3.6          install bluebird#2.3.11

    react#0.12.2 bower_components/react

    react-router#1.0.2 bower_components/react-router

    bluebird#2.3.11 bower_components/bluebird

But brunch fails:

    $ brunch watch --server

    15 Dec 18:36:19 - error: [Error: Component JSON file "/Users/tieme/Projects/exim/examples/chat/bower_components/react-router/.bower.json" must have `main` property. See https://github.com/paulmillr/read-components#README]
    15 Dec 18:36:20 - error: Initialization error - [Error: You probably need to execute `npm install` to install brunch plugins. Error: Cannot find module 'coffee-script']

osx: 10.11.2
node: v5.0.0
npm: 3.3.12

**Comment by paulmillr** [comment]
Great catch. We'll fix this one.

**Comment by stelmakh** [comment]
Hi @tiemevanveen. Thanks for reporting the issue. It should be fixed with https://github.com/hellyeahllc/exim/pull/53

**Comment by tiemevanveen** [comment]
Nice, thanks for fixing this so quickly. Build succeeds now example works like a charm.

**Comment by stelmakh** [comment]
Glad to hear it, thanks :+1:
